print('Olá mundo')
print('Socorro')
print('SOS')
print('minha casa')
print ('Help me')
print('não aguento mais')
print('SONO')
print('Muito sono')
print('Odeio acordar cedo')
print('preciso de dinheiro')